import { useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  FiUser,
  FiSend,
  FiDownload,
  FiBriefcase,
} from "react-icons/fi";
import { SiOpenai } from "react-icons/si";
import CVPreviewCard from "../components/CVPreviewCard";

export default function AICVRewriter() {

  const navigate = useNavigate();

  // Candidate Data (Later this can come from API)
  const [candidate, setCandidate] = useState({
    name: "John Smith",
    job_title: "Senior Software Developer",
  });

  const [isRewriting, setIsRewriting] = useState(false);

  const [options, setOptions] = useState({
    removeSurname: true,
    replaceWithRef: false,
    removeEmployer: false,
  });

  const originalCV = `
JOHN SMITH
Senior Software Developer

Email: john.smith@email.com | Phone: +44 7700 900123

PROFESSIONAL SUMMARY
Experienced software developer with 5+ years of expertise in building scalable applications.
Proven track record at TechCorp International delivering high-quality solutions.

WORK EXPERIENCE
Senior Developer – TechCorp International (2021–Present)
- Led development of microservices architecture
- Improved application performance by 40%

EDUCATION
BSc Computer Science – University of Technology
`;

  const [aiCV, setAiCV] = useState(`
JOHN
Senior Software Developer

Email: anonymized@email.com | Phone: +44 7700 900123

PROFESSIONAL SUMMARY
Experienced software developer with strong expertise in enterprise application development.
Demonstrated ability to build scalable, high-performance systems.

WORK EXPERIENCE
Senior Developer – Leading Technology Company (2021–Present)
- Designed and implemented scalable architectures
- Improved system performance and maintainability

EDUCATION
BSc Computer Science – University of Technology
`);

  const handleRewriteWithAI = () => {
    setIsRewriting(true);

    setTimeout(() => {

      const firstName = candidate.name.split(" ")[0].toUpperCase();

      const rewrittenCV = `
${options.removeSurname ? firstName : candidate.name.toUpperCase()}
${candidate.job_title}

Email: anonymized@email.com | Phone: +44 7700 900123

PROFESSIONAL SUMMARY
AI-enhanced CV generated by ChatGPT focusing on clarity, impact, and recruiter-friendly structure.

WORK EXPERIENCE
Senior Developer – ${
        options.removeEmployer
          ? "Leading Technology Company"
          : "TechCorp International"
      } (2021–Present)

- Architected scalable systems
- Improved performance and maintainability
- Collaborated with cross-functional teams

EDUCATION
BSc Computer Science – University of Technology
`;

      setAiCV(rewrittenCV);
      setIsRewriting(false);
    }, 1500);
  };

  return (
    <div className="p-4 sm:p-6">

      {/* Page Header */}
      <div className="mb-6">
        <h1 className="text-xl sm:text-2xl md:text-3xl font-bold text-[#2D468A]">
          AI CV Rewriter & Anonymization
        </h1>

        <p className="text-sm text-gray-600 mt-1 max-w-2xl">
          Enhance CVs with AI and apply anonymization settings
        </p>
      </div>

      {/* Candidate Info */}
      <div className="bg-white/60 p-4 rounded-lg border mb-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">

          {/* Candidate Name */}
          <div className="space-y-2">
            <label className="text-sm font-medium text-gray-700 flex items-center gap-2">
              <FiUser className="text-gray-400" />
              Candidate
            </label>

            <input
              type="text"
              value={candidate.name}
              readOnly
              className="w-full rounded-xl border border-gray-300 bg-gray-50 px-4 py-3 text-gray-700"
            />
          </div>

          {/* Job Title */}
          <div className="space-y-2">
            <label className="text-sm font-medium text-gray-700 flex items-center gap-2">
              <FiBriefcase className="text-gray-400" />
              Job Title
            </label>

            <input
              type="text"
              value={candidate.job_title}
              readOnly
              className="w-full rounded-xl border border-gray-300 bg-gray-50 px-4 py-3 text-gray-700"
            />
          </div>

        </div>
      </div>

      <div className="bg-white/60 p-4 sm:p-6 md:p-8 mb-8 rounded-lg shadow-sm">

        {/* AI Rewrite Button */}
        <div className="inline-block border border-gray-100 rounded-xl p-3 bg-white">
          <button
            onClick={handleRewriteWithAI}
            disabled={isRewriting}
            className={`px-4 py-3 rounded-md text-sm flex items-center gap-2
              ${
                isRewriting
                  ? "bg-gray-400 text-white cursor-not-allowed"
                  : "bg-[#2D468A] text-white hover:bg-[#243a73]"
              }`}
          >
            <SiOpenai />
            {isRewriting ? "AI is rewriting..." : "Rewrite with AI"}
          </button>
        </div>

        {/* CV Preview */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6 pt-6 sm:pt-8">

          <CVPreviewCard
            title="Original CV"
            status="Before AI processing"
            content={originalCV}
          />

          <CVPreviewCard
            title="AI-Enhanced CV"
            status="Processed by ChatGPT"
            content={aiCV}
          />

        </div>

        {/* Actions */}
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-4 pt-6 sm:pt-8">

          <button
            onClick={() => navigate("/ai/mail-submission")}
            className="flex-1 bg-[#2D468B] text-white px-6 py-3 rounded-md hover:bg-[#354e92] flex items-center justify-center gap-2"
          >
            <FiSend />
            Mail Submission
          </button>

          <button className="border border-gray-300 px-6 py-3 rounded-md text-sm text-black hover:text-white hover:bg-[#2D468B] flex items-center justify-center gap-2">
            <FiDownload />
            Download CV
          </button>

        </div>

      </div>
    </div>
  );
}