import { useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  FiUser,
  FiSend,
  FiDownload,
} from "react-icons/fi";
import { SiOpenai } from "react-icons/si";

import AnonymizationOption from "../components/AnonymizationOption";
import CVPreviewCard from "../components/CVPreviewCard";

export default function AICVRewriter() {
  /* ---------------- Navigation ---------------- */
  const navigate = useNavigate();

  /* ---------------- State ---------------- */
  const [selectedCandidate, setSelectedCandidate] = useState("John Smith");
  const [isRewriting, setIsRewriting] = useState(false);

  const [options, setOptions] = useState({
    removeSurname: true,
    replaceWithRef: false,
    removeEmployer: false,
  });

  /* ---------------- Dummy CV Data ---------------- */
  const originalCV = `
JOHN SMITH
Senior Software Developer

Email: john.smith@email.com | Phone: +44 7700 900123

PROFESSIONAL SUMMARY
Experienced software developer with 5+ years of expertise in building scalable applications.
Proven track record at TechCorp International delivering high-quality solutions.

WORK EXPERIENCE
Senior Developer – TechCorp International (2021–Present)
- Led development of microservices architecture
- Improved application performance by 40%

EDUCATION
BSc Computer Science – University of Technology
`;

  const [aiCV, setAiCV] = useState(`
JOHN
Senior Software Developer

Email: anonymized@email.com | Phone: +44 7700 900123

PROFESSIONAL SUMMARY
Experienced software developer with strong expertise in enterprise application development.
Demonstrated ability to build scalable, high-performance systems.

WORK EXPERIENCE
Senior Developer – Leading Technology Company (2021–Present)
- Designed and implemented scalable architectures
- Improved system performance and maintainability

EDUCATION
BSc Computer Science – University of Technology
`);

  /* ---------------- ChatGPT Dummy Rewrite ---------------- */
  const handleRewriteWithAI = () => {
    setIsRewriting(true);

    // ⏳ Simulate ChatGPT thinking
    setTimeout(() => {
      const firstName = selectedCandidate.split(" ")[0].toUpperCase();

      const rewrittenCV = `
${options.removeSurname ? firstName : selectedCandidate.toUpperCase()}
Senior Software Developer

Email: anonymized@email.com | Phone: +44 7700 900123

PROFESSIONAL SUMMARY
AI-enhanced CV generated by ChatGPT focusing on clarity, impact, and
recruiter-friendly structure. Optimized for modern hiring standards.

WORK EXPERIENCE
Senior Developer – ${
        options.removeEmployer
          ? "Leading Technology Company"
          : "TechCorp International"
      } (2021–Present)
- Architected scalable, maintainable frontend systems
- Improved performance and code quality using best practices
- Collaborated effectively with cross-functional teams

EDUCATION
BSc Computer Science – University of Technology
`;

      setAiCV(rewrittenCV);
      setIsRewriting(false);
    }, 1500);
  };

  return (
    <div className="p-4 sm:p-6">
      {/* 🔹 Page Header */}
      <div className="mb-6">
        <h1 className="text-xl sm:text-2xl md:text-3xl font-bold text-[#2D468A]">
          AI CV Rewriter & Anonymization
        </h1>
        <p className="text-sm text-gray-600 mt-1 max-w-2xl">
          Enhance CVs with AI and apply anonymization settings
        </p>
      </div>

      {/* 🔹 Candidate Select */}
      <div className="bg-white/60 p-4 rounded-lg border mb-6">
        <div className="space-y-2">
          <label className="text-sm font-medium text-gray-700 mb-2 flex items-center gap-2">
            <FiUser className="text-gray-400" />
            Candidate
          </label>

          <input
            type="text"
            value="John Smith"
            readOnly
            className="w-full rounded-xl border border-gray-300 bg-gray-50 px-4 py-3 text-gray-700 focus:outline-none"
          />
        </div>

        {/* <select
          value={selectedCandidate}
          onChange={(e) => setSelectedCandidate(e.target.value)}
          className="w-full border rounded-md px-4 py-2.5 text-sm text-gray-800 cursor-pointer
          focus:outline-none focus:ring-2 focus:ring-[#2D468B]"
        >
          <option>John Smith</option>
          <option>Emily Carter</option>
          <option>Michael Brown</option>
        </select> */}
      </div>

      {/* 🔹 Anonymization Settings */}
      <div className="bg-white/60 p-4 sm:p-6 md:p-8 mb-8 rounded-lg shadow-sm">
        {/* <div className="bg-white/60 rounded-lg shadow-md border border-gray-200 mb-6 p-4 sm:p-6">
          <h3 className="text-xl font-semibold text-[#2D468A] mb-4">
            Anonymization Settings
          </h3>

          <div className="flex flex-col gap-4">
            <AnonymizationOption
              title="Remove Surname"
              description="Keep first name only"
              checked={options.removeSurname}
              onChange={() =>
                setOptions((p) => ({
                  ...p,
                  removeSurname: !p.removeSurname,
                }))
              }
            />

            <AnonymizationOption
              title="Replace with Database Reference"
              description="Use candidate reference ID instead of name"
              checked={options.replaceWithRef}
              onChange={() =>
                setOptions((p) => ({
                  ...p,
                  replaceWithRef: !p.replaceWithRef,
                }))
              }
            />

            <AnonymizationOption
              title="Remove Current Employer Name"
              description="Replace with generic company description"
              checked={options.removeEmployer}
              onChange={() =>
                setOptions((p) => ({
                  ...p,
                  removeEmployer: !p.removeEmployer,
                }))
              }
            />
          </div> 
        </div> */}

        {/* Rewrite Button (ChatGPT) */}
        <div className="inline-block border border-gray-200 rounded-xl p-2 bg-white">
          <button
            onClick={handleRewriteWithAI}
            disabled={isRewriting}
            className={`px-3 py-4 rounded-md text-sm transition flex items-center gap-2 cursor-pointer
      ${
        isRewriting
          ? "bg-gray-400 text-white cursor-not-allowed"
          : "bg-[#2D468A] text-white hover:bg-[#243a73]"
      }
    `}
          >
            <SiOpenai className="text-base" />
            {isRewriting ? "ChatGPT is rewriting..." : "Rewrite with ChatGPT"}
          </button>
        </div>

        {/* 🔹 CV Comparison */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6 pt-6 sm:pt-8">
          <CVPreviewCard
            title="Original CV"
            status="Before AI processing"
            content={originalCV}
          />

          <CVPreviewCard
            title="AI-Enhanced CV"
            status="Processed by ChatGPT"
            content={aiCV}
          />
        </div>

        {/* 🔹 Footer Actions */}
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-4 pt-6 sm:pt-8">
          <button
            onClick={() => navigate("/mail/submission")}
            className="flex-1 bg-[#2D468B] text-white px-6 py-3 rounded-md cursor-pointer hover:bg-[#354e92] flex items-center justify-center gap-2"
          >
            <FiSend />
            Mail Submission
          </button>

          <button className="border border-gray-300 px-6 py-3 rounded-md text-sm text-black cursor-pointer hover:bg-gray-300 transition-all flex items-center justify-center gap-2">
            <FiDownload />
            Download CV
          </button>
        </div>
      </div>
    </div>
  );
}
